M48
; DRILL file {KiCad 9.0.7} date 2026-02-16T18:05:01-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-16T18:05:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X157.5Y-92.25
T2
X157.5Y-87.75
T3
X153.84Y-47.65
X196.53Y-90.44
M30
